# Generated by Django 6.0.4 on 2026-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
